spring:
  application:
    name: chatcourse
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes in milliseconds
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:root@localhost}
      database: chatcourse
    redis:
      host: localhost
      port: 6379



server:
  port: 3030
app:
  auth:
    jwks-url: ${JWKS_URL:http://localhost:8081/.well-known/jwks.json}